site_name: jinko docs
repo_url: https://github.com/jinko-core/jinko
theme:
  name: material
  palette:
    - primary: teal
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Code blocks
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
